// Generated by CoffeeScript 1.12.7
let domToMarkup, objectToSaneObject, saneObjectToDom, self;

objectToSaneObject = require("./objectToSaneObject");

saneObjectToDom = require("./saneObjectToDom");

domToMarkup = require("./domToMarkup");

import { object } from "#utila";

module.exports = self = {
  objectToDom: function (o) {
    o = self._object2SaneObject(o);
    return saneObjectToDom.convert(o);
  },
  object2markup: function (o) {
    let dom;
    dom = self.objectToDom(o);
    return domToMarkup.convert(dom);
  },
  domToMarkup: function (dom) {
    return domToMarkup.convert(dom);
  },
  _object2SaneObject: function (o) {
    if (!Array.isArray(o)) {
      if (!object.isBareObject(o)) {
        throw Error("toDom() only accepts arrays and bare objects as input");
      }
    }
    return objectToSaneObject.sanitize(o);
  },
};
